CREATE TABLE Species (
	Name VARCHAR(20) NOT NULL,
	PRIMARY KEY (Name),
	IsEndangered Boolean NOT NULL,
	AvgLifespan INT NOT NULL,
	AvgLbs INT NOT NULL
);

CREATE TABLE Zoos (
	City VARCHAR(20) NOT NULL,
	PRIMARY KEY (City)
	Country VARCHAR(20) NOT NULL,
	Acres INT NOT NULL,
	Year_Founded INT NOT NULL
);

CREATE TABLE Animals (
	Name VARCHAR(20) NOT NULL,
	Species VARCHAR(20) NOT NULL,
	Zoo VARCHAR(20) NOT NULL,
	YearBorn INT NOT NULL
	CONSTRAINT Species
		FOREIGN KEY (Species)
		REFERENCES Extra_Credit.Species (Name)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT Zoo
		FOREIGN KEY (Zoo)
		REFERENCES Extra_Credit.Zoos (City)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);


INSERT INTO